- name: config template /etc/collectd/collectd.conf
  template:
    src: config/collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    mode: 0644
  notify:
    - collectd service collectd restarted
